<?php

namespace App\Services\Ai;

use App\Repositories\CategoryRepository;
use App\Services\GeminiService;

class ProductContentService
{
    public function __construct(
        private GeminiService $geminiService,
        private CategoryRepository $categories,
    ) {
    }

    public function draft(string $promptInput): array
    {
        $categoriesList = implode(', ', $this->categories->names());

        $prompt = "Generate optimized e-commerce product listing information based on this product idea: '{$promptInput}'.\n"
            . "Recommend one of these existing store categories if possible: {$categoriesList}.\n"
            . "Create a professional title, a competitive suggested price, the recommended category, an engaging HTML-formatted description outlining key features, specs, and care tips, and a list of comma-separated search/SEO tags.";

        $systemInstruction = "You are a professional e-commerce product catalog manager. Respond ONLY with valid JSON matching this schema:\n"
            . "{\n"
            . "  \"name\": \"Optimized Title\",\n"
            . "  \"title\": \"Optimized Title\",\n"
            . "  \"price\": 39.99,\n"
            . "  \"category_suggestion\": \"Electronics\",\n"
            . "  \"description\": \"<p>Product Description in clean HTML</p>\",\n"
            . "  \"tags\": \"tag1, tag2, tag3\"\n"
            . "}\n"
            . "Do not write markdown outside of the JSON block.";

        $result = $this->geminiService->generateContent($prompt, $systemInstruction, true);
        $result = is_array($result) ? $result : [];

        return [
            'name' => $result['name'] ?? $result['title'] ?? 'AI Optimized Product',
            'title' => $result['title'] ?? $result['name'] ?? 'AI Optimized Product',
            'price' => (float) ($result['price'] ?? 49.99),
            'category_suggestion' => $result['category_suggestion'] ?? ($this->categories->names()[0] ?? 'General'),
            'description' => $result['description'] ?? '<p>Premium product listing generated by AI.</p>',
            'tags' => $result['tags'] ?? 'premium, quality, marketplace',
        ];
    }

    public function title(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['title' => $draft['title']];
    }

    public function description(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['description' => $draft['description']];
    }

    public function category(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['category_suggestion' => $draft['category_suggestion']];
    }

    public function tags(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['tags' => $draft['tags']];
    }

    public function price(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['price' => $draft['price']];
    }
}
