<?php

namespace App\Services\Ai;

use App\Repositories\CategoryRepository;
use App\Services\GeminiService;

class ProductContentService
{
    public function __construct(
        private GeminiService $geminiService,
        private CategoryRepository $categories,
    ) {
    }

    public function draft(string $promptInput): array
    {
        $categoriesList = implode(', ', $this->categories->names());

        $prompt = "Generate optimized e-commerce product listing information based on this product idea: '{$promptInput}'.\n"
            . "Recommend one of these existing store categories if possible: {$categoriesList}.\n"
            . "Create a professional title, a realistic competitive suggested price in USD, the recommended category, an engaging plain-text description outlining key features, specs, and care tips, and a list of comma-separated search/SEO tags.\n"
            . "Do not suggest unrealistically low prices for premium electronics, phones, laptops, tablets, or branded-style products. Flagship phones should usually be priced in the hundreds or thousands, not under $100.";

        $systemInstruction = "You are a professional e-commerce marketplace analyst. Think like a real seller assistant: use the product name, features, quality tier, likely customer, and category before writing. If information is missing, make conservative assumptions and do not invent brand claims.\n"
            . "Respond ONLY with valid JSON matching this schema:\n"
            . "{\n"
            . "  \"name\": \"Optimized Title\",\n"
            . "  \"title\": \"Optimized Title\",\n"
            . "  \"price\": 1199.00,\n"
            . "  \"price_reason\": \"Short reason for the suggested price\",\n"
            . "  \"category_suggestion\": \"Electronics\",\n"
            . "  \"description\": \"Plain text product description\",\n"
            . "  \"tags\": \"tag1, tag2, tag3\"\n"
            . "}\n"
            . "Do not write markdown outside of the JSON block.";

        $result = $this->geminiService->generateContent($prompt, $systemInstruction, true);
        $result = is_array($result) ? $result : [];

        return $this->normalizeDraft([
            'name' => $result['name'] ?? $result['title'] ?? 'AI Optimized Product',
            'title' => $result['title'] ?? $result['name'] ?? 'AI Optimized Product',
            'price' => (float) ($result['price'] ?? 49.99),
            'price_reason' => $result['price_reason'] ?? null,
            'category_suggestion' => $result['category_suggestion'] ?? ($this->categories->names()[0] ?? 'General'),
            'description' => strip_tags($result['description'] ?? 'Premium product listing generated by AI.'),
            'tags' => $result['tags'] ?? 'premium, quality, marketplace',
        ], $promptInput);
    }

    public function title(string $prompt): array
    {
        $result = $this->geminiService->generateContent(
            "Create one high-converting ecommerce product title from these product details:\n{$prompt}",
            "Return ONLY valid JSON: {\"title\":\"Premium Wireless RGB Gaming Mouse\"}. Keep the title under 70 characters, clear, searchable, and not spammy.",
            true
        );
        $result = is_array($result) ? $result : [];

        return ['title' => $result['title'] ?? $this->draft($prompt)['title']];
    }

    public function description(string $prompt): array
    {
        $result = $this->geminiService->generateContent(
            "Write a practical ecommerce product description from these product details:\n{$prompt}",
            "Return ONLY valid JSON: {\"description\":\"Experience precision gaming...\"}. Use plain text only, 1 short intro paragraph, then 3-5 simple benefit lines. Do not return HTML or markdown. Avoid fake claims.",
            true
        );
        $result = is_array($result) ? $result : [];

        return ['description' => strip_tags($result['description'] ?? $this->draft($prompt)['description'])];
    }

    public function category(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['category_suggestion' => $draft['category_suggestion']];
    }

    public function tags(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['tags' => $draft['tags']];
    }

    public function seoKeywords(string $prompt): array
    {
        $result = $this->geminiService->generateContent(
            "Generate buyer-search SEO keywords for this ecommerce product:\n{$prompt}",
            "Return ONLY valid JSON: {\"keywords\":[\"wireless gaming mouse\",\"rgb mouse\",\"16000 dpi mouse\"],\"tags\":\"wireless gaming mouse, rgb mouse, 16000 dpi mouse\"}. Include 8-12 useful search phrases, no duplicates.",
            true
        );
        $result = is_array($result) ? $result : [];

        $keywords = $result['keywords'] ?? [];
        if (!is_array($keywords) || count($keywords) === 0) {
            $tags = $this->draft($prompt)['tags'];
            $keywords = array_values(array_filter(array_map('trim', explode(',', $tags))));
        }

        return [
            'keywords' => $keywords,
            'tags' => $result['tags'] ?? implode(', ', $keywords),
        ];
    }

    public function price(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return [
            'price' => $draft['price'],
            'price_reason' => $draft['price_reason'] ?? 'Suggested from product type and features.',
        ];
    }

    private function normalizeDraft(array $draft, string $prompt): array
    {
        $priceCheck = $this->realisticPrice((float) ($draft['price'] ?? 0), $prompt . ' ' . ($draft['name'] ?? '') . ' ' . ($draft['category_suggestion'] ?? ''));
        $title = $this->normalizeTitle($draft['title'] ?? $draft['name'] ?? 'AI Optimized Product');

        return [
            'name' => $title,
            'title' => $title,
            'price' => $priceCheck['price'],
            'price_reason' => $draft['price_reason'] ?: $priceCheck['reason'],
            'category_suggestion' => $draft['category_suggestion'] ?? ($this->categories->names()[0] ?? 'General'),
            'description' => trim(strip_tags($draft['description'] ?? 'Premium product listing generated by AI.')),
            'tags' => $this->normalizeTags($draft['tags'] ?? 'premium, quality, marketplace'),
        ];
    }

    private function realisticPrice(float $suggestedPrice, string $context): array
    {
        $text = strtolower($context);
        $feedbackPrice = $this->extractFeedbackPrice($context);
        if ($feedbackPrice !== null) {
            return [
                'price' => $feedbackPrice,
                'reason' => 'Adjusted from seller feedback and market record provided in the AI correction.',
            ];
        }

        $rules = [
            ['match' => ['iphone 7 plus'], 'min' => 60.00, 'max' => 140.00, 'fallback' => 99.00, 'reason' => 'iPhone 7 Plus is an older discontinued model and is usually positioned as used or refurbished.'],
            ['match' => ['iphone 7'], 'min' => 40.00, 'max' => 120.00, 'fallback' => 69.00, 'reason' => 'iPhone 7 is an older discontinued model, so realistic marketplace pricing is usually used/refurbished budget pricing.'],
            ['match' => ['iphone 8 plus'], 'min' => 80.00, 'max' => 180.00, 'fallback' => 129.00, 'reason' => 'iPhone 8 Plus is discontinued and should usually be priced as used or refurbished.'],
            ['match' => ['iphone 8'], 'min' => 70.00, 'max' => 160.00, 'fallback' => 109.00, 'reason' => 'iPhone 8 is discontinued and should usually be priced as used or refurbished.'],
            ['match' => ['iphone', 'pro max'], 'min' => 999.00, 'fallback' => 1199.00, 'reason' => 'Flagship iPhone Pro Max products are premium electronics, so the price should usually be in the high hundreds or thousands.'],
            ['match' => ['iphone'], 'min' => 699.00, 'fallback' => 899.00, 'reason' => 'iPhone products are premium smartphones and should not be priced like low-cost accessories.'],
            ['match' => ['smartphone'], 'min' => 199.00, 'fallback' => 499.00, 'reason' => 'Smartphones normally require a mid-to-high price range depending on specs.'],
            ['match' => ['phone'], 'min' => 199.00, 'fallback' => 499.00, 'reason' => 'Phones normally require a mid-to-high price range depending on specs.'],
            ['match' => ['macbook'], 'min' => 899.00, 'fallback' => 1299.00, 'reason' => 'MacBook-style products are premium laptops and need premium pricing.'],
            ['match' => ['laptop'], 'min' => 399.00, 'fallback' => 799.00, 'reason' => 'Laptops should be priced based on hardware tier, not accessory pricing.'],
            ['match' => ['ipad'], 'min' => 349.00, 'fallback' => 599.00, 'reason' => 'iPad-style tablets are premium devices and should not be priced under accessory levels.'],
            ['match' => ['tablet'], 'min' => 199.00, 'fallback' => 399.00, 'reason' => 'Tablets usually sit above small accessory pricing.'],
            ['match' => ['gaming mouse'], 'min' => 29.00, 'fallback' => 79.99, 'reason' => 'Gaming mice with performance features usually sit above basic mouse pricing.'],
        ];

        foreach ($rules as $rule) {
            $matches = collect($rule['match'])->every(fn ($needle) => str_contains($text, $needle));
            if ($matches && ($suggestedPrice < $rule['min'] || (isset($rule['max']) && $suggestedPrice > $rule['max']))) {
                return ['price' => $rule['fallback'], 'reason' => $rule['reason']];
            }
        }

        return [
            'price' => $suggestedPrice > 0 ? round($suggestedPrice, 2) : 49.99,
            'reason' => 'Suggested from the product type, features, and expected marketplace tier.',
        ];
    }

    private function normalizeTitle(string $title): string
    {
        $title = trim(preg_replace('/\s+/', ' ', strip_tags($title)));
        $title = preg_replace('/\biphone\b/i', 'iPhone', $title);
        $title = preg_replace('/\bipad\b/i', 'iPad', $title);
        $title = preg_replace('/\bmacbook\b/i', 'MacBook', $title);
        $title = preg_replace('/\bpromax\b/i', 'Pro Max', $title);
        $title = preg_replace('/\bpro max\b/i', 'Pro Max', $title);

        return $title;
    }

    private function normalizeTags(string $tags): string
    {
        return collect(explode(',', $tags))
            ->map(fn ($tag) => strtolower(trim($tag)))
            ->filter()
            ->unique()
            ->take(12)
            ->implode(', ');
    }

    private function extractFeedbackPrice(string $context): ?float
    {
        if (!str_contains(strtolower($context), 'seller feedback')) {
            return null;
        }

        if (preg_match_all('/\\$?([0-9]+(?:\\.[0-9]{1,2})?)/', $context, $matches) && count($matches[1]) > 0) {
            $values = array_map('floatval', $matches[1]);

            return round(array_sum($values) / count($values), 2);
        }

        return null;
    }
}
