<?php

namespace App\Services\Ai;

use App\Repositories\CategoryRepository;
use App\Services\GeminiService;

class ProductContentService
{
    public function __construct(
        private GeminiService $geminiService,
        private CategoryRepository $categories,
    ) {
    }

    public function draft(string $promptInput): array
    {
        $categoriesList = implode(', ', $this->categories->names());

        $prompt = "Generate optimized e-commerce product listing information based on this product idea: '{$promptInput}'.\n"
            . "Recommend one of these existing store categories if possible: {$categoriesList}.\n"
            . "Create a professional title, a competitive suggested price, the recommended category, an engaging HTML-formatted description outlining key features, specs, and care tips, and a list of comma-separated search/SEO tags.";

        $systemInstruction = "You are a professional e-commerce product catalog manager. Respond ONLY with valid JSON matching this schema:\n"
            . "{\n"
            . "  \"name\": \"Optimized Title\",\n"
            . "  \"title\": \"Optimized Title\",\n"
            . "  \"price\": 39.99,\n"
            . "  \"category_suggestion\": \"Electronics\",\n"
            . "  \"description\": \"<p>Product Description in clean HTML</p>\",\n"
            . "  \"tags\": \"tag1, tag2, tag3\"\n"
            . "}\n"
            . "Do not write markdown outside of the JSON block.";

        $result = $this->geminiService->generateContent($prompt, $systemInstruction, true);
        $result = is_array($result) ? $result : [];

        return [
            'name' => $result['name'] ?? $result['title'] ?? 'AI Optimized Product',
            'title' => $result['title'] ?? $result['name'] ?? 'AI Optimized Product',
            'price' => (float) ($result['price'] ?? 49.99),
            'category_suggestion' => $result['category_suggestion'] ?? ($this->categories->names()[0] ?? 'General'),
            'description' => $result['description'] ?? '<p>Premium product listing generated by AI.</p>',
            'tags' => $result['tags'] ?? 'premium, quality, marketplace',
        ];
    }

    public function title(string $prompt): array
    {
        $result = $this->geminiService->generateContent(
            "Create one high-converting ecommerce product title from these product details:\n{$prompt}",
            "Return ONLY valid JSON: {\"title\":\"Premium Wireless RGB Gaming Mouse\"}. Keep the title under 70 characters, clear, searchable, and not spammy.",
            true
        );
        $result = is_array($result) ? $result : [];

        return ['title' => $result['title'] ?? $this->draft($prompt)['title']];
    }

    public function description(string $prompt): array
    {
        $result = $this->geminiService->generateContent(
            "Write a practical ecommerce product description from these product details:\n{$prompt}",
            "Return ONLY valid JSON: {\"description\":\"<p>Experience precision gaming...</p>\"}. Use clean HTML, 1 short intro paragraph, then 3-5 benefit bullets. Avoid fake claims.",
            true
        );
        $result = is_array($result) ? $result : [];

        return ['description' => $result['description'] ?? $this->draft($prompt)['description']];
    }

    public function category(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['category_suggestion' => $draft['category_suggestion']];
    }

    public function tags(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['tags' => $draft['tags']];
    }

    public function seoKeywords(string $prompt): array
    {
        $result = $this->geminiService->generateContent(
            "Generate buyer-search SEO keywords for this ecommerce product:\n{$prompt}",
            "Return ONLY valid JSON: {\"keywords\":[\"wireless gaming mouse\",\"rgb mouse\",\"16000 dpi mouse\"],\"tags\":\"wireless gaming mouse, rgb mouse, 16000 dpi mouse\"}. Include 8-12 useful search phrases, no duplicates.",
            true
        );
        $result = is_array($result) ? $result : [];

        $keywords = $result['keywords'] ?? [];
        if (!is_array($keywords) || count($keywords) === 0) {
            $tags = $this->draft($prompt)['tags'];
            $keywords = array_values(array_filter(array_map('trim', explode(',', $tags))));
        }

        return [
            'keywords' => $keywords,
            'tags' => $result['tags'] ?? implode(', ', $keywords),
        ];
    }

    public function price(string $prompt): array
    {
        $draft = $this->draft($prompt);

        return ['price' => $draft['price']];
    }
}
